### ISSUE TITLE
Start REPL with server

### ISSUE THREAD

**Issue by logc** [arvyy/kawa-maven-plugin#3]
Is there a way to issue `mvn kawa:repl` and pass an argument like `--server=37146` to the Kawa process? This could allow to connect to the process from Emacs' Geiser and evaluate Scheme functions that import project dependencies.

**Comment by logc** [comment]
Thanks! If there is another way to accomplish the same, please let me know.

**Comment by logc** [comment]
I have read the doc with more care and found `repl-command`. This command works:
```
mvn kawa:repl -Drepl-command=java,-Dkawa.import.path=@KAWAIMPORT@SEPARATOR@PROJECTROOT/src/main/scheme,kawa.repl,--server,9999
```

**Comment by logc** [comment]
There is a proposed enhancement in PR #4 to do the same as above but with a shorter command:

```
mvn kawa:repl -Drepl-server=9999
```

**Comment by arvyy** [comment]
#4
