### ISSUE TITLE
How to set command line flags to Kawa via the plugin?

### ISSUE THREAD

**Issue by duncanmak** [arvyy/kawa-maven-plugin#6]
Did the `<configuration>` support change in one of the versions?

I used to have:

```
<plugin>
  <groupId>com.github.arvyy>/groupId>
  <artifactId>kawa-maven-plugin</artifactId>
  
   <configuration>
       <warnUnused>false</warnUnused>
   </configuration>
</plugin>
```

That doesn't seem to work now? Is the new way to set the `<compileCommand>`?

**Comment by arvyy** [comment]
> That doesn't seem to work now? Is the new way to set the <compileCommand>?

Yes, the intent is to make plugin future-proof and invoke kawa transparently

**Comment by duncanmak** [comment]
I see, is there a way to set the kawa.jar if I want to use a build from git instead of a release?

**Comment by arvyy** [comment]
The designed way is to install built kawa.jar into local repository using eg. `mvn install:install-file -Dfile=kawa.jar -DgroupId=kawa -DartifactId=kawa -Dversion=3.1.1-2022-09-18 -Dpackaging=jar`, which you'd then be able to add as a dependency

```
<dependency>
    <groupId>kawa</groupId>
    <artifactId>kawa</artifactId>
    <version>3.1.1-2022-09-18</version>
</dependency>
```

**Comment by arvyy** [comment]
@duncanmak did you manage to get it working? If so, can we close this issue

**Comment by duncanmak** [comment]
Thanks @arvyy, it's all good now!
