### ISSUE TITLE
Configurable source and target Directories

### ISSUE THREAD

**Issue by gmwesiga** [arvyy/kawa-maven-plugin#7]
Am unable to configure the plugin's source and target directories via the <build> element. looking at the code, it seems this structure is hard-coded. Is it possible to modify this?

**Comment by gmwesiga** [comment]
** via the build element

**Comment by arvyy** [comment]
The structure isn't hardcoded (the code you saw provides default value, but they are overrideable). It's configured under plugin's entry under plugins tag, not directly under build tag. An example from docs:

```
<project>
  <build>
    <plugins>
        <plugin>
            <groupId>com.github.arvyy</groupId>
            <artifactId>kawa-maven-plugin</artifactId>
            <version>VERSION</version>
            <configuration>
                <compileCommand>
                    <str>java</str>
                    <str>-Dkawa.import.path=@KAWAIMPORT@SEPARATOR@PROJECTROOT/src/main/scheme</str>
                    <str>kawa.repl</str>
                    <str>-d</str>
                    <str>@PROJECTROOT/target/classes</str>
                    <str>--main</str>
                    <str>-C</str>
                    <str>@PROJECTROOT/src/main/scheme/main.scm</str>
                </compileCommand>
            </configuration>
```

you should be able to replace lines `<str>-Dkawa.import.path=@KAWAIMPORT@SEPARATOR@PROJECTROOT/src/main/scheme</str>` and `<str>@PROJECTROOT/target/classes</str>` with something else.

**Comment by gmwesiga** [comment]
Thank you. now it's clear to me.
